name: expense_tracker
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

flutter_icons:
  android: true
  ios: true
  image_path: "lib/asset/icon/icon.png"

flutter_native_splash:
  color: "#00695C"
  image: lib/asset/icon/icon.png

  android: true
  ios: true
  web: false

  android_gravity: center
  ios_content_mode: scaleAspectFill



environment:
  sdk: '>=2.19.6 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # Firebase realated dependencies
  firebase_core: ^2.9.0
  firebase_auth: ^4.0.1
  cloud_firestore: ^4.13.6

  # Flutter dependencies
  flutter_native_image: ^0.0.6+1
  flutter_bloc: ^8.1.1
  flutter_keyboard_visibility: ^5.0.2
  google_maps_flutter: ^2.2.0
  flutter_animation_progress_bar: ^2.0.0
  flutter_downloader: ^1.7.1
  flutter_secure_storage: ^8.1.0
  fl_chart: ^0.55.2

  # Third party dependencies
  carousel_slider: ^4.0.0
  logger: ^2.6.0
  pdf: ^3.6.3
  localstorage: ^4.0.0+1
  location: ^5.0.3
  pin_code_fields: ^8.0.1
  crypto: ^3.0.3



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  auto_size_text: ^3.0.0
  url_launcher: ^6.1.11
  uuid: ^4.1.0
  google_sign_in: ^6.1.6
  go_router: ^12.1.1
  intl: ^0.18.1
  dropdown_button2: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: 2.2.19

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/asset/images/lock.jpg
    - lib/asset/images/earth.jpg
    - lib/asset/images/star.jpg
    - lib/asset/images/space.jpg
    - lib/asset/images/techWall.jpg
    - lib/asset/images/shultter.jpg
    - lib/asset/images/landing/bar_graph.png
    - lib/asset/images/landing/progress_graph.png
    - lib/asset/images/landing/cash.png
    - lib/asset/images/landing/coins.png
    - lib/asset/images/landing/calculator.png
    - lib/asset/images/landing/money.png
    - lib/asset/images/landing/money_management.png
    - lib/asset/images/bg/black-solid.jpg
    - lib/asset/images/bg/solid-black.jpg
    - lib/asset/images/bg/sky-blue.jpg
    - lib/asset/images/bg/gradient.jpg
    - lib/asset/icon/google_icon.jpeg
    
    
  fonts:
    # 1) Roboto
    - family: Roboto
      fonts:
        - asset: lib/asset/fonts/Roboto/Regular.ttf
          weight: 400
        - asset: lib/asset/fonts/Roboto/Bold.ttf
          weight: 700

    # 2) Montserrat
    - family: Montserrat
      fonts:
        - asset: lib/asset/fonts/Montserrat/Regular.ttf
          weight: 400
        - asset: lib/asset/fonts/Montserrat/SemiBold.ttf
          weight: 600
        - asset: lib/asset/fonts/Montserrat/Bold.ttf
          weight: 700
        - asset: lib/asset/fonts/Montserrat/ExtraBold.ttf
          weight: 800
        - asset: lib/asset/fonts/Montserrat/Black.ttf
          weight: 900

    # 3) DancingScript
    - family: DancingScript
      fonts:
        - asset: lib/asset/fonts/DancingScript/Regular.ttf
          weight: 400
        - asset: lib/asset/fonts/DancingScript/Medium.ttf
          weight: 500
        - asset: lib/asset/fonts/DancingScript/SemiBold.ttf
          weight: 600
        - asset: lib/asset/fonts/DancingScript/Bold.ttf
          weight: 700

    # 4) OpenSans
    - family: OpenSans
      fonts:
        - asset: lib/asset/fonts/OpenSans/Regular.ttf
          weight: 400
        - asset: lib/asset/fonts/OpenSans/Bold.ttf
          weight: 700
        - asset: lib/asset/fonts/OpenSans/Light_Italic.ttf
          weight: 300
          style: italic
        - asset: lib/asset/fonts/OpenSans/Condensed_Italic.ttf
          weight: 400
          style: italic

    # 5) Pacifico
    - family: Pacifico
      fonts:
        - asset: lib/asset/fonts/Pacifico/Regular.ttf
          weight: 400

    # 6) PlayfairDisplay
    - family: PlayfairDisplay
      fonts:
        - asset: lib/asset/fonts/PlayfairDisplay/Regular.ttf
          weight: 400
        - asset: lib/asset/fonts/PlayfairDisplay/Italic.ttf
          weight: 400
          style: italic
        - asset: lib/asset/fonts/PlayfairDisplay/Bold.ttf
          weight: 700
        - asset: lib/asset/fonts/PlayfairDisplay/Black_Italic.ttf
          weight: 900
          style: italic
